### ISSUE TITLE
data_utils

### ISSUE THREAD

**Issue by luobotaxinghu** [dongjun-Lee/text-classification-models-tf#3]
data_utils.py  function build_char_dataset

some seem not very reasonable:

    when model = "char_cnn":  
        char_dict["<pad>"] = char_dict["<unk>"] = char_dict["a"] = 0 after onehot in char_cnn.py

    when model = "vd_cnn": 
        char_dict["<pad>"] = char_dict["a"] = 0, 
        char_dict["<unk>"] = char_dict["b"] = 1

**Comment by dongjun-Lee** [comment]
Thanks for your review. Fixed in 768ea13547104f56786c52f0c6eb99912c816a09.
